# Use official Python image
FROM python:3.10-slim

# Install OS-level dependencies: Tesseract and Poppler
RUN apt-get update && apt-get install -y \
    tesseract-ocr-nep \
    poppler-utils \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy all files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose Streamlit port
EXPOSE 8501

# Run Streamlit app
CMD ["streamlit", "run", "pdftoexcel-interface.py", "--server.port=8501", "--server.address=0.0.0.0"]
