services:
  - type: web
    name: nepali-pdf-to-excel
    env: python
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils tesseract-ocr
      pip install -r requirements.txt
    startCommand: streamlit run pdftoexcel-interface.py --server.port=$PORT
